from game import Game
from square import Square

# フィールドチップクラス（画面１マスのクラス）
class Chip(Square):
    # チップ（フィールドの１マス）画像のリスト
    images = None
    
    # コンストラクタ
    def __init__(self):
        # Ａ－１３Squareから）親クラスのコンストラクタを呼び出す
        super().__init__()
        # Ａ－１４）チップ番号に初期値を設定
        self.chip_no = 0
        # Ａ－１５）画像リストが空の場合（初回のみ）
        if Chip.images == None:
            # Ａ－１６）チップ（フィールドの部品）画像を読み込み
            Chip.images = (
                Game.read_image_for_square('image/chip0.png'),
                Game.read_image_for_square('image/chip1.png'),
                Game.read_image_for_square('image/chip2.png'),
                Game.read_image_for_square('image/chip3.png'),
                Game.read_image_for_square('image/chip4.png'),
                Game.read_image_for_square('image/chip5.png'),
                Game.read_image_for_square('image/chip6.png'),
                Game.read_image_for_square('image/chip7.png'),
                Game.read_image_for_square('image/chip8.png'),
                Game.read_image_for_square('image/chip9.png'),
                Game.read_image_for_square('image/chip10.png'),
                Game.read_image_for_square('image/chip11.png'),
                Game.read_image_for_square('image/chip12.png'),
                Game.read_image_for_square('image/chip13.png'),
                Game.read_image_for_square('image/chip14.png'),
                Game.read_image_for_square('image/chip15.png'),
                Game.read_image_for_square('image/chip16.png'),
                Game.read_image_for_square('image/chip17.png'),
                Game.read_image_for_square('image/chip18.png'),
                Game.read_image_for_square('image/chip19.png'),
                Game.read_image_for_square('image/chip20.png'),
                Game.read_image_for_square('image/chip21.png'),
                Game.read_image_for_square('image/chip22.png'),
                Game.read_image_for_square('image/chip23.png'),
                Game.read_image_for_square('image/chip17.png'),
                Game.read_image_for_square('image/chip25.png'),
                Game.read_image_for_square('image/chip26.png'),
                Game.read_image_for_square('image/chip27.png'),
                Game.read_image_for_square('image/chip28.png'),
                Game.read_image_for_square('image/chip29.png'),
                Game.read_image_for_square('image/chip30.png'),
                Game.read_image_for_square('image/chip31.png'),
                Game.read_image_for_square('image/chip32.png'),
                Game.read_image_for_square('image/chip33.png'),
                Game.read_image_for_square('image/chip34.png'),
                Game.read_image_for_square('image/chip35.png'),
                Game.read_image_for_square('image/chip16.png'),
                Game.read_image_for_square('image/chip17.png'),
                Game.read_image_for_square('image/chip17.png'),
                Game.read_image_for_square('image/chip17.png'),
                Game.read_image_for_square('image/chip40.png'),
                Game.read_image_for_square('image/chip41.png'),
                Game.read_image_for_square('image/chip42.png'),
                Game.read_image_for_square('image/chip43.png'),
                Game.read_image_for_square('image/chip44.png'),
                Game.read_image_for_square('image/chip45.png'),
                Game.read_image_for_square('image/chip46.png'),
                Game.read_image_for_square('image/chip47.png'),
                Game.read_image_for_square('image/chip48.png'),
                Game.read_image_for_square('image/chip49.png'),
                Game.read_image_for_square('image/chip50.png'),
                Game.read_image_for_square('image/chip51.png'),
                Game.read_image_for_square('image/chip52.png'),
                Game.read_image_for_square('image/chip53.png'),
                Game.read_image_for_square('image/chip54.png'),
                Game.read_image_for_square('image/chip55.png'),
                Game.read_image_for_square('image/chip56.png'),
                Game.read_image_for_square('image/chip57.png'),
                Game.read_image_for_square('image/chip58.png'),
                Game.read_image_for_square('image/chip59.png'),
                Game.read_image_for_square('image/chip60.png'),
                Game.read_image_for_square('image/chip61.png'),
                Game.read_image_for_square('image/chip62.png'),
                Game.read_image_for_square('image/chip63.png'),
                Game.read_image_for_square('image/chip64.png'),
                Game.read_image_for_square('image/chip65.png'),
                Game.read_image_for_square('image/chip66.png'),
                Game.read_image_for_square('image/chip67.png'),
                Game.read_image_for_square('image/chip68.png'),
                Game.read_image_for_square('image/chip69.png'),
                Game.read_image_for_square('image/chip70.png'),
                Game.read_image_for_square('image/chip71.png'),
                Game.read_image_for_square('image/chip72.png'),
                Game.read_image_for_square('image/chip73.png'),
                Game.read_image_for_square('image/chip74.png'),
                Game.read_image_for_square('image/chip75.png'),
                Game.read_image_for_square('image/chip76.png'),
                Game.read_image_for_square('image/chip73.png'),
                Game.read_image_for_square('image/chip73.png'),
                Game.read_image_for_square('image/chip79.png'),
                Game.read_image_for_square('image/chip80.png'),
                Game.read_image_for_square('image/chip81.png'),
                Game.read_image_for_square('image/chip82.png'),
                Game.read_image_for_square('image/chip83.png'),
                Game.read_image_for_square('image/chip84.png'),
                Game.read_image_for_square('image/chip85.png'),
                Game.read_image_for_square('image/chip86.png'),
                Game.read_image_for_square('image/chip87.png'),
                Game.read_image_for_square('image/chip88.png'),
                Game.read_image_for_square('image/chip89.png'),
                Game.read_image_for_square('image/chip90.png'),
                Game.read_image_for_square('image/chip91.png'),
                Game.read_image_for_square('image/chip92.png'),
                Game.read_image_for_square('image/chip93.png'),
                Game.read_image_for_square('image/chip94.png'),
                Game.read_image_for_square('image/chip95.png'),
                Game.read_image_for_square('image/chip96.png'),
                Game.read_image_for_square('image/chip97.png'),
                Game.read_image_for_square('image/chip98.png'),
                Game.read_image_for_square('image/chip99.png'),
                Game.read_image_for_square('image/chip100.png'),
                Game.read_image_for_square('image/chip101.png'),
                Game.read_image_for_square('image/chip102.png'),
                Game.read_image_for_square('image/chip103.png'),
                Game.read_image_for_square('image/chip104.png'),
                Game.read_image_for_square('image/chip105.png'),
                Game.read_image_for_square('image/chip106.png'),
                Game.read_image_for_square('image/chip107.png'),
                Game.read_image_for_square('image/chip93.png'),
                Game.read_image_for_square('image/chip93.png'),
                Game.read_image_for_square('image/chip110.png'),
                Game.read_image_for_square('image/chip111.png'),
                Game.read_image_for_square('image/chip112.png'),
                Game.read_image_for_square('image/chip113.png'),
                Game.read_image_for_square('image/chip114.png'),
                Game.read_image_for_square('image/chip115.png'),
                Game.read_image_for_square('image/chip116.png'),
                Game.read_image_for_square('image/chip117.png'),
            )
    
    # チップ番号設定
    def set_chip_no(self, no):
        # Ａ－１７）引数の番号を設定
        self.chip_no = no
        # Ａ－１８Fieldへ）番号に対応する画像を設定
        self.set_image(self.images[no])
